"""15 verbatim Cascade tool definitions (LANAAGNT-IN02 transcription, IS-06).

GENERATED from _INFO_CASCADE_TOOL_DEFINITIONS.md [LANAAGNT-IN02] (generator script `.tmp_generate_definitions.py` was single-run temp, recoverable from git history).
Descriptions are [LITERAL] - never hand-edit; regenerate from IN02 instead. tests/test_definitions_diff.py guards the zero-diff contract.
Substitution points: {OS}/{SHELL} in run_command, {SKILL_LIST} in skill (applied by render_definitions).
"""
import json

DESCRIPTION_TEMPLATES = {
  "read_file": "Reads a file at the specified relative path.\nThis tool is only able to read files in the workspace that are not gitignored.\nIf the User provides a path to a file assume that path is valid. It is okay to read a file that does not exist; an error will be returned.\n\nUsage:\n- The file_path parameter must be an absolute path, not a relative path\n- You can optionally specify a line offset and limit to read files that are larger than 1000 lines. For other files, do not provide these parameters to read the whole file.\n- Any lines longer than 2000 characters will be truncated\n- Text files are returned with 1-indexed line numbers in cat -n format\n- Image files (jpg, jpeg, png, gif, bmp, webp, svg, tiff, ico, heic, heif) are automatically presented visually\n- You have the capability to call multiple tools in a single response. It is always better to speculatively read multiple files as a batch that are potentially useful.\n- You will regularly be asked to read screenshots. If the user provides a path to a screenshot ALWAYS use this tool to view the file at the path. This tool will work with all temporary file paths like /var/folders/123/abc/T/TemporaryItems/NSIRD_screencaptureui_ZfB1tD/Screenshot.png\n- If you read a file that exists but has empty contents you will receive a system reminder warning in place of file contents.",
  "list_dir": "Lists files and directories in a given path. The path parameter must be an absolute path to a directory that exists. For each item in the directory, output will have: relative path to the file or directory, and size in bytes if file or number of items (recursive) if directory. You should generally prefer the find_by_name and grep_search tools, if you know which directories to search.",
  "grep_search": "A powerful search tool built on ripgrep\n\nUsage:\n- NEVER invoke `grep` or `rg` as a Bash command, use this tool instead. The Grep tool has\nbeen optimized for correct permissions and access.\n- DO NOT USE MatchPerLine for initial searches that may have a large number of results. Use it only when you\nknow it is a very specific, targeted search.\n- By default, Query is treated as a regular expression. Set FixedStrings to true to treat Query as a literal string (no regex).\n- Filter files with Includes parameter in glob format (e.g., \"*.js\", \"**/*.tsx\")\n- If the result is truncated, you must narrow down your search using a more specific query or more filters.",
  "find_by_name": "Search for files and subdirectories within a specified directory using fd.\nSearch uses smart case and will ignore gitignored files by default.\nPattern and Excludes both use the glob format. If you are searching for Extensions, there is no need to specify both Pattern AND Extensions.\nTo avoid overwhelming output, the results are capped at 50 matches. Use the various arguments to filter the search scope as needed.\nResults will include the type, size, modification time, and relative path.",
  "edit": "Performs exact string replacements in files.\n\nUsage:\n- You must use your `Read` tool at least once in the conversation before editing. This tool will error if you attempt an edit without reading the file.\n- When editing text from Read tool output, ensure you preserve the exact indentation (tabs/spaces) as it appears AFTER the line number prefix. The line number prefix format is: spaces + line number + tab. Everything after that tab is the actual file content to match. Never include any part of the line number prefix in the old_string or new_string.\n- ALWAYS prefer editing existing files in the codebase. NEVER write new files unless explicitly required.\n- Only use emojis if the user explicitly requests it. Avoid adding emojis to files unless asked.\n- The edit will FAIL if `old_string` is not unique in the file. Either provide a larger string with more surrounding context to make it unique or use `replace_all` to change every instance of `old_string`.\n- Use `replace_all` for replacing and renaming strings across the file. This parameter is useful if you want to rename a variable for instance.\n- The edit will FAIL if `old_string` and `new_string` are identical. This is considered a no-op and will throw an error.\n- Include an `explanation` field to describe the change you are making.\nIMPORTANT: You must generate the following arguments first, before any others: [file_path]",
  "multi_edit": "This is a tool for making multiple edits to a single file in one operation. It is built on top of the Edit tool and allows you to perform multiple find-and-replace operations efficiently. Prefer this tool over the Edit tool when you need to make multiple edits to the same file.\n\nBefore using this tool:\n\n1. Use the Read tool to understand the file's contents and context\n2.Verify the directory path is correct\n\nTo make multiple file edits, provide the following: \n1.file_path: The path to the file to modify, relative to the root of the repository\n2.edits: An array of edit operations to perform, where each edit contains: \n   - old_string: The text to replace(must match the file contents exactly, including all whitespace and indentation) \n - new_string: The edited text to replace the old_string\n - replace_all: Replace all occurrences of old_string.This parameter is optional and defaults to false.\n3.explanation: A description of the change to be made\n\nIMPORTANT: \n - All edits are applied in sequence, in the order they are provided\n - Each edit operates on the result of the previous edit\n - All edits must be valid for the operation to succeed - if any edit fails, none will be applied\n - This tool is ideal when you need to make several changes to different parts of the same file\n - For Jupyter notebooks(.ipynb files), use the NotebookEdit instead\n\nCRITICAL REQUIREMENTS: \n1.All edits follow the same requirements as the single Edit tool\n2.The edits are atomic - either all succeed or none are applied\n3.Plan your edits carefully to avoid conflicts between sequential operations\n\nWARNING: \n - The tool will fail if edits.old_string doesn't match the file contents exactly (including whitespace)\n- The tool will fail if edits.old_string and edits.new_string are the same\n- Since edits are applied in sequence, ensure that earlier edits don't affect the text that later edits are trying to find\n\nWhen making edits: \n - Ensure all edits result in idiomatic, correct code\n - Do not leave the code in a broken state\n - Always use absolute file paths(starting with /) \n - Only use emojis if the user explicitly requests it.Avoid adding emojis to files unless asked.\n - Use replace_all for replacing and renaming strings across the file.This parameter is useful if you want to rename a variable for instance.\n\nIf you want to create a new file, use: \n - A new file path, including dir name if needed\n - First edit: empty old_string and the new file's contents as new_string\n- Subsequent edits: normal edit operations on the created content\nIMPORTANT: You must generate the following arguments first, before any others: [file_path]",
  "write_to_file": "Use this tool to create new files. The file and any parent directories will be created for you if they do not already exist.\n\t\tFollow these instructions:\n\t\t1. NEVER use this tool to modify or overwrite existing files. Always first confirm that TargetFile does not exist before calling this tool.\n\t\t2. You MUST specify the full TargetFile before any of the code contents.\nIMPORTANT: You must generate the following arguments first, before any others: [TargetFile]",
  "run_command": "PROPOSE a command to run on behalf of the user. Operating System: {OS}. Shell: {SHELL}.\n**NEVER PROPOSE A cd COMMAND**.\nIf you have this tool, note that you DO have the ability to run commands directly on the USER's system.\nMake sure to specify CommandLine exactly as it should be run in the shell.\nNote that the user will have to approve the command before it is executed. The user may reject it if it is not to their liking.\nThe actual command will NOT execute until the user approves it. The user may not approve it immediately.\nIf the step is WAITING for user approval, it has NOT started running.\nCommands will be run with PAGER=cat. You may want to limit the length of output for commands that usually rely on paging and may contain very long output (e.g. git log, use git log -n <N>).",
  "command_status": "Check the status of a previously started terminal command by its ID. Returns the current status (running or done), output lines as specified by output priority, and any error if present. If WaitDurationSeconds is specified, this tool will also wait up to that many seconds for the command to finish. Otherwise, this tool will directly return the current status of the command. Do not try to check the status of any IDs other than Background command IDs.",
  "todo_list": "Use this tool to create, update, or manage a todo list. This tool helps you organize tasks with different statuses and priorities. You can add new todos, update existing ones, mark them as completed, or reorganize the entire list.\n\nThe tool accepts a list of todo items, each with:\n- content: The task description\n- status: pending, in_progress, or completed\n- priority: high, medium, or low\n- id: A unique identifier for the todo item\n\nUse this tool when you need to:\n- Create a new todo list (mark the first item as in_progress to indicate what you're currently working on)\n- Add items to an existing todo list\n- Update the status of todo items\n- Change priorities of tasks\n- Mark tasks as completed\n- Reorganize or restructure the todo list",
  "skill": "Invoke a skill to get detailed instructions or knowledge for a task.\nUse this when a task matches a skill's description.\nAvailable skills:\n{SKILL_LIST}",
  "ask_user_question": "Ask the user a question with predefined options. Use this when you need the user to make a choice between specific options.\nYou can provide up to 4 options, each with a label and description.\nNEVER include \"other\" as an option - the user can always automatically provide a custom response.\nSet allowMultiple to true if the user should be able to select more than one option.",
  "search_web": "Performs a web search to get a list of relevant web documents for the given query and optional domain filter.",
  "read_url_content": "Read content from a URL. URL must be an HTTP or HTTPS URL that points to a valid internet resource accessible via web browser.\nNote that the user will have to approve the web request before it is fetched. The user may reject it if it is not to their liking.\nThe actual fetch will NOT execute until the user approves it. The user may not approve it immediately.",
  "view_content_chunk": "View a specific chunk of a web or knowledge base document content using its DocumentId and chunk position. The DocumentId must have already been read by the read_url_content tool before this can be used on that particular DocumentId.",
}

SCHEMAS = {
  "read_file": {'type': 'object', 'additionalProperties': False, 'properties': {'file_path': {'type': 'string'}, 'offset': {'type': 'integer'}, 'limit': {'type': 'integer'}}, 'required': ['file_path']},
  "list_dir": {'type': 'object', 'additionalProperties': False, 'properties': {'DirectoryPath': {'type': 'string'}}, 'required': ['DirectoryPath']},
  "grep_search": {'type': 'object', 'additionalProperties': False, 'properties': {'SearchPath': {'type': 'string'}, 'Query': {'type': 'string'}, 'CaseSensitive': {'type': 'boolean'}, 'FixedStrings': {'type': 'boolean'}, 'Includes': {'type': 'array', 'items': {'type': 'string'}}, 'MatchPerLine': {'type': 'boolean'}}, 'required': ['SearchPath', 'Query']},
  "find_by_name": {'type': 'object', 'additionalProperties': False, 'properties': {'SearchDirectory': {'type': 'string'}, 'Pattern': {'type': 'string'}, 'Excludes': {'type': 'array', 'items': {'type': 'string'}}, 'Extensions': {'type': 'array', 'items': {'type': 'string'}}, 'FullPath': {'type': 'boolean'}, 'MaxDepth': {'type': 'integer'}, 'Type': {'type': 'string', 'enum': ['file', 'directory', 'any']}}, 'required': ['SearchDirectory', 'Pattern']},
  "edit": {'type': 'object', 'additionalProperties': False, 'properties': {'explanation': {'type': 'string'}, 'file_path': {'type': 'string'}, 'old_string': {'type': 'string'}, 'new_string': {'type': 'string'}, 'replace_all': {'type': 'boolean'}}, 'required': ['file_path', 'old_string', 'new_string']},
  "multi_edit": {'type': 'object', 'additionalProperties': False, 'properties': {'explanation': {'type': 'string'}, 'file_path': {'type': 'string'}, 'edits': {'type': 'array', 'minItems': 1, 'items': {'type': 'object', 'additionalProperties': False, 'properties': {'old_string': {'type': 'string'}, 'new_string': {'type': 'string'}, 'replace_all': {'type': 'boolean'}}, 'required': ['old_string', 'new_string']}}}, 'required': ['file_path', 'edits']},
  "write_to_file": {'type': 'object', 'additionalProperties': False, 'properties': {'TargetFile': {'type': 'string'}, 'CodeContent': {'type': 'string'}, 'EmptyFile': {'type': 'boolean'}}, 'required': ['TargetFile', 'CodeContent', 'EmptyFile']},
  "run_command": {'type': 'object', 'additionalProperties': False, 'properties': {'CommandLine': {'type': 'string'}, 'Cwd': {'type': 'string'}, 'Blocking': {'type': 'boolean'}, 'SafeToAutoRun': {'type': 'boolean'}, 'WaitMsBeforeAsync': {'type': 'integer'}}, 'required': ['CommandLine']},
  "command_status": {'type': 'object', 'additionalProperties': False, 'properties': {'CommandId': {'type': 'string'}, 'OutputCharacterCount': {'type': 'integer'}, 'WaitDurationSeconds': {'type': 'integer', 'default': 0}}, 'required': ['CommandId', 'OutputCharacterCount']},
  "todo_list": {'type': 'object', 'additionalProperties': False, 'properties': {'todos': {'type': 'array', 'items': {'type': 'object', 'additionalProperties': False, 'properties': {'id': {'type': 'string'}, 'content': {'type': 'string'}, 'status': {'type': 'string', 'enum': ['pending', 'in_progress', 'completed']}, 'priority': {'type': 'string', 'enum': ['high', 'medium', 'low']}}, 'required': ['id', 'content', 'status', 'priority']}}}, 'required': ['todos']},
  "skill": {'type': 'object', 'additionalProperties': False, 'properties': {'SkillName': {'type': 'string'}}, 'required': ['SkillName']},
  "ask_user_question": {'type': 'object', 'additionalProperties': False, 'properties': {'question': {'type': 'string'}, 'options': {'type': 'array', 'items': {'type': 'object', 'additionalProperties': False, 'properties': {'label': {'type': 'string'}, 'description': {'type': 'string'}}, 'required': ['label', 'description']}}, 'allowMultiple': {'type': 'boolean'}}, 'required': ['question', 'options', 'allowMultiple']},
  "search_web": {'type': 'object', 'additionalProperties': False, 'properties': {'query': {'type': 'string'}, 'domain': {'type': 'string'}}, 'required': ['query']},
  "read_url_content": {'type': 'object', 'additionalProperties': False, 'properties': {'Url': {'type': 'string'}}, 'required': ['Url']},
  "view_content_chunk": {'type': 'object', 'additionalProperties': False, 'properties': {'document_id': {'type': 'string'}, 'position': {'type': 'integer'}}, 'required': ['document_id', 'position']},
}


TOOL_NAMES = list(DESCRIPTION_TEMPLATES)


# Deterministic serialization for cache stability (IS-06): sorted keys, compact separators
def schema_json(name: str) -> str:
  return json.dumps(SCHEMAS[name], sort_keys=True, separators=(",", ":"))


def render_skill_list(skills) -> str:
  entries = []
  for skill in skills:
    file_count = len(skill.supporting_files)
    suffix = f" ({file_count} supporting file" + ("s" if file_count != 1 else "") + ")" if file_count else ""
    entries.append(f"- {skill.name}: {skill.description}{suffix}")
  return "\n".join(entries)


def render_definitions(os_name: str, shell: str, skills) -> list[dict]:
  """
  Produce the finalized tool definitions with substitution points filled.

  Example item: {"name": "read_file", "description": "Reads a file...", "schema": {...}}
  """
  rendered = []
  for name in TOOL_NAMES:
    description = DESCRIPTION_TEMPLATES[name]
    if name == "run_command": description = description.replace("{OS}", os_name).replace("{SHELL}", shell)
    if name == "skill": description = description.replace("{SKILL_LIST}", render_skill_list(skills))
    rendered.append({"name": name, "description": description, "schema": SCHEMAS[name]})
  return rendered
